name: Build ReVanced

on: workflow_dispatch

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Get last tag
        id: last_tag
        uses: oprypin/find-latest-tag@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          releases-only: true

      - name: Set default tag if none exists
        if: steps.last_tag.outputs.tag == ''
        run: echo "NEXT_VER_CODE=1" >> $GITHUB_OUTPUT

      - name: Get next version code
        id: next_ver_code
        run: |
          TAG="${{ steps.last_tag.outputs.tag }}"
          if [ -z "$TAG" ]; then TAG=0; fi
          echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT

      - name: Set execute permission for build script
        run: chmod +x build.sh

      - name: Build APK
        run: |
          git pull
          ./build.sh config.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}

      - name: Get output
        id: get_output
        run: |
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"
          yt_v=$(cat build.md | grep "YouTube-Extended:" | head -n 1 | cut -d " " -f 2)
          ytm_v=$(cat build.md | grep "Music-Extended:" | head -n 1 | cut -d " " -f 2)
          if [ -z "$yt_v" ]; then
            echo "RELEASE_NAME=YouTube ReVanced" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_NAME=YouTube:v$yt_v Music:v$ytm_v" >> $GITHUB_OUTPUT
          fi

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          body: ${{ steps.get_output.outputs.BUILD_LOG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*
          release_name: ${{ steps.get_output.outputs.RELEASE_NAME }}
          tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
          file_glob: true
          overwrite: true

      - name: Upload APKs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: revanced-apks
          path: ./build/*.apk

  deploy:
    needs: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download APKs
        uses: actions/download-artifact@v3
        with:
          name: revanced-apks
          path: ./releases

      - name: Update script.js
        run: |
          echo "var apkList = [];" > script.js  # Initialize an empty JS array
          for apk in ./releases/*; do
            apk_name=$(basename "$apk")
            echo "apkList.push('$apk_name');" >> script.js  # Add each APK to the array
          done

      - name: Commit and push updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add releases/
          git add script.js
          git commit -m "Update APKs for version v${{ needs.run.outputs.NEXT_VER_CODE }}"
          git push origin gh-pages
